[workspace]
members = ["string-width", "ansi-align", "boxen-rs-bin"]
resolver = "2"

[workspace.dependencies]
unicode-width = "0.1"
strip-ansi-escapes = "0.2"
string-width = { path = "string-width" }
ansi-align = { path = "ansi-align" }
