[workspace]
members = ["string-width", "boxen-rs-bin"]

[workspace.dependencies]
unicode-width = "0.2.1"
strip-ansi-escapes = "0.2.1"

string-width = { path = "string-width" }
boxen-rs-bin = { path = "boxen-rs-bin" }
